<?php
require_once __DIR__.'/../includes/bootstrap.php';
require_role('Admin');
$pdo=db();
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='tambah'){csrf_verify();$un=trim($_POST['username']??'');$nm=trim($_POST['nama_lengkap']??'');$pw=(string)($_POST['password']??'');$pw2=(string)($_POST['password2']??'');$err=[];if(strlen($un)<3)$err[]='Username min 3.';if($nm==='')$err[]='Nama wajib.';if(strlen($pw)<6)$err[]='Password min 6.';if($pw!==$pw2)$err[]='Password tidak cocok.';if(!$err){$c=$pdo->prepare('SELECT COUNT(*) FROM users WHERE username=?');$c->execute([$un]);if($c->fetchColumn()>0)$err[]='Username sudah ada.';}if($err)flash('error',implode(' ',$err));else{$pdo->prepare('INSERT INTO users(username,password,nama_lengkap,role)VALUES(?,?,?,?)')-> execute([$un,password_hash($pw,PASSWORD_DEFAULT),$nm,'Petugas']);flash('success','Petugas ditambahkan.');}redirect('admin/pengguna.php');}
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='edit'){csrf_verify();$id=(int)($_POST['id_user']??0);$un=trim($_POST['username']??'');$nm=trim($_POST['nama_lengkap']??'');$pw=(string)($_POST['password']??'');$err=[];if($un==='')$err[]='Username wajib.';if($nm==='')$err[]='Nama wajib.';if(!$err){$c=$pdo->prepare('SELECT COUNT(*) FROM users WHERE username=? AND id_user<>?');$c->execute([$un,$id]);if($c->fetchColumn()>0)$err[]='Username sudah ada.';}if($err)flash('error',implode(' ',$err));else{if($pw!==''&&strlen($pw)>=6){$pdo->prepare('UPDATE users SET username=?,nama_lengkap=?,password=? WHERE id_user=? AND role="Petugas"')->execute([$un,$nm,password_hash($pw,PASSWORD_DEFAULT),$id]);}else{$pdo->prepare('UPDATE users SET username=?,nama_lengkap=? WHERE id_user=? AND role="Petugas"')->execute([$un,$nm,$id]);}flash('success','Data diperbarui.');}redirect('admin/pengguna.php');}
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='hapus'){csrf_verify();$id=(int)($_POST['id_user']??0);if($id>0){$pdo->prepare('DELETE FROM users WHERE id_user=? AND role="Petugas"')->execute([$id]);flash('success','Akun dihapus.');}redirect('admin/pengguna.php');}
$list=$pdo->query("SELECT u.*,COUNT(h.id_deteksi) AS jml FROM users u LEFT JOIN history_deteksi h ON h.id_user=u.id_user WHERE u.role='Petugas' GROUP BY u.id_user ORDER BY u.nama_lengkap")->fetchAll();
$page_title='Manajemen Pengguna';$active_menu='pengguna';
require __DIR__.'/../includes/header.php';
?>
<div class="d-flex justify-content-between align-items-center mb-3 flex-wrap gap-2"><p class="text-muted mb-0">CRUD akun petugas.</p><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalTambah"><i class="bi bi-person-plus"></i> Tambah</button></div>
<div class="card"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>#</th><th>Username</th><th>Nama</th><th class="text-center">Deteksi</th><th class="text-end">Aksi</th></tr></thead><tbody>
<?php if(!$list):?><tr><td colspan="5" class="text-center text-muted py-4">Belum ada petugas.</td></tr>
<?php else:foreach($list as $i=>$r):?><tr><td><?=$i+1?></td><td><code><?=e($r['username'])?></code></td><td><?=e($r['nama_lengkap'])?></td><td class="text-center"><span class="badge bg-secondary"><?=(int)$r['jml']?></span></td><td class="text-end"><button class="btn btn-sm btn-outline-primary btn-edit" data-id="<?=(int)$r['id_user']?>" data-username="<?=e($r['username'])?>" data-nama="<?=e($r['nama_lengkap'])?>" data-bs-toggle="modal" data-bs-target="#modalEdit"><i class="bi bi-pencil"></i></button> <form method="post" class="d-inline" onsubmit="return confirm('Hapus?')"><?=csrf_field()?><input type="hidden" name="action" value="hapus"><input type="hidden" name="id_user" value="<?=(int)$r['id_user']?>"><button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr>
<?php endforeach;endif;?></tbody></table></div></div>
<div class="modal fade" id="modalTambah" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" method="post"><?=csrf_field()?><input type="hidden" name="action" value="tambah"><div class="modal-header"><h5 class="modal-title">Tambah Petugas</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label">Username</label><input type="text" name="username" class="form-control" required></div><div class="mb-3"><label class="form-label">Nama Lengkap</label><input type="text" name="nama_lengkap" class="form-control" required></div><div class="mb-3"><label class="form-label">Password</label><input type="password" name="password" class="form-control" required minlength="6"></div><div class="mb-3"><label class="form-label">Ulangi Password</label><input type="password" name="password2" class="form-control" required></div></div><div class="modal-footer"><button type="submit" class="btn btn-primary">Simpan</button></div></form></div></div>
<div class="modal fade" id="modalEdit" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" method="post"><?=csrf_field()?><input type="hidden" name="action" value="edit"><input type="hidden" name="id_user" id="edit-id"><div class="modal-header"><h5 class="modal-title">Edit Petugas</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label">Username</label><input type="text" name="username" id="edit-username" class="form-control" required></div><div class="mb-3"><label class="form-label">Nama Lengkap</label><input type="text" name="nama_lengkap" id="edit-nama" class="form-control" required></div><div class="mb-3"><label class="form-label">Password Baru (kosongkan jika tidak diubah)</label><input type="password" name="password" class="form-control"></div></div><div class="modal-footer"><button type="submit" class="btn btn-primary">Simpan</button></div></form></div></div>
<?php $extra_js='<script>document.querySelectorAll(".btn-edit").forEach(b=>{b.addEventListener("click",()=>{document.getElementById("edit-id").value=b.dataset.id;document.getElementById("edit-username").value=b.dataset.username;document.getElementById("edit-nama").value=b.dataset.nama;});});</script>';
require __DIR__.'/../includes/footer.php';?>
